config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'

  resources :players, except: :destroy

  get 'ping_pong', to: 'ping_pong#home', as: 'ping_pong'
  get 'ping_pong/games', to: redirect('ping_pong'), as: 'ping_pong_alt'
  get 'ping_pong/games/new', to: 'ping_pong#new_game', as: 'new_ping_pong_game'
  post 'ping_pong/games', to: 'ping_pong#create_game', as: 'ping_pong_games'

end

app/models/ping_pong_game.rb
class PingPongGame < ActiveRecord::Base
  validates :date, presence: true
  validates :player_one_score, numericality: { only_integer: true, greater_than_or_equal_to: 0, message: "must be a non-negative integer" }
  validates :player_two_score, numericality: { only_integer: true, greater_than_or_equal_to: 0, message: "must be a non-negative integer" }
  validate :players_are_different

  belongs_to :player_one, class_name: 'Player', foreign_key: 'player_one_id'
  belongs_to :player_two, class_name: 'Player', foreign_key: 'player_two_id'

  def players_are_different
    self.errors.add(:base, 'The two players must be different') if self.player_one_id == self.player_two_id
  end

end

app/models/player.rb
class Player < ActiveRecord::Base
  validates :name, presence: true

  has_many :ping_pong_games_as_player_one, class_name: 'PingPongGame', foreign_key: :player_one_id
  has_many :ping_pong_games_as_player_two, class_name: 'PingPongGame', foreign_key: :player_two_id

  def ping_pong_games
    (ping_pong_games_as_player_one.all + ping_pong_games_as_player_two.all).uniq
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ping_pong_controller.rb
class PingPongController < ApplicationController

  def home
    @ping_pong_games = PingPongGame.last(10).reverse
    @power_ranks = Player.all.map { |player| [player.name, power_rank(player.id)] }
  end

  def new_game
    @ping_pong_game = PingPongGame.new
    @players = Player.all
  end

  def create_game
    @ping_pong_game = PingPongGame.new(game_params)

    if @ping_pong_game.save
      redirect_to ping_pong_path
    else
      @players = Player.all
      render :new_game
    end
  end

  private
    def game_params
      params.require(:ping_pong_game).permit(:date, :player_one_score, :player_two_score, :player_one_id, :player_two_id)
    end

    def pvp_rank(player_a_id, player_b_id)
      @player_a = Player.find(player_a_id)
      @player_b = Player.find(player_b_id)

      games = (@player_a.ping_pong_games & @player_b.ping_pong_games).uniq
    
      if games.count < 5
        return 0
      else
        wins = 0.0

        games.each do |g|
          if g.player_one_id == @player_a.id and g.player_one_score > g.player_two_score
            wins += 1
          elsif g.player_two_id == @player_a.id and g.player_one_score < g.player_two_score
            wins += 1
          end
        end

        win_percentage = wins / games.count

        return win_percentage
      end
    end

    def power_rank_chain(players)
      factor = 1
      if players.length > 2
        for i in 0..(players.length - 2)
          factor = factor * pvp_rank(players[i].id,players[i+1].id)
        end
      end
      puts factor
      return factor
    end

    def power_rank(player_id)
      @player = Player.find(player_id)

      opponents = Player.where.not(id: player_id)

      rank = 0.0

      opponents.permutation.each do |perm|
        rank = rank + pvp_rank(@player.id, perm[0].id)*power_rank_chain(perm)
      end


      return rank*100
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    @players = Player.all
  end

  def new
    @player = Player.new
  end

  def show
    @player = Player.find(params[:id])
  end
  
  def create
    @player = Player.new(player_params)

    if @player.save
      redirect_to players_path
    else
      render :new
    end
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])

    if @player.update(player_params)
      redirect_to @player
    else
      render :edit
    end
  end

  private
    def player_params
      params.require(:player).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="title">
  <h1><%= Scoreboard::Application.config.app_name.upcase %></h1>
</div>

app/views/layouts/_top_bar.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to Scoreboard::Application.config.app_name.upcase, root_path %></h1>
    </li>

    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <li><%= link_to 'ping pong', ping_pong_path %></li>
      <li><%= link_to 'players', players_path %></li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />

    <title><%= Scoreboard::Application.config.app_name.upcase %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render partial: 'layouts/top_bar' %>
    
    <div class="row wrapper">

    <%= yield %>

    </div>
  </body>
</html>

app/views/layouts/foundation5.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/ping_pong/_form.html.erb
<%= simple_form_for :ping_pong_game, url: target, method: method do |f| %>
  <% if ping_pong_game.errors.any? %>
    <% ping_pong_game.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  <% end %>

  <%= f.input :date, as: 'date' %>
  <%= f.input :player_one_id, collection: players %>
  <%= f.input :player_one_score, label: 'score' %>
  <%= f.input :player_two_id, collection: players %>
  <%= f.input :player_two_score, label: 'score' %>

  <div class="center form-button-container">
    <%= f.button :button, 'save', type: "submit", class: "button round" %>
    <%= link_to 'cancel', cancel, class: "button round" %>
  </div>

<% end %>

app/views/ping_pong/home.html.erb
<div class="title">
  <h2>ping pong</h2>
</div>

<div class="list">
  <div class="list_item center">
    <h4>power rankings</h4>
  </div>

  <% @power_ranks.each do |player_name, rank| %>
  <div class="list_item center">
    <div class="power_ranking_name">
      <span><%= player_name %></span>
    </div>
    <div class="power_ranking">
      <span><%= '%.0f' % rank %></span>
    </div>
  </div>
  <% end %>
</div>

<div id="ping_pong_game_list">
  <div class="ping_pong_game_list_item center">
    <h4>recent games</h4>
  </div>
<% @ping_pong_games.each do |g| %>
  <div class="ping_pong_game_list_item" id="ping_pong_game_<%= g.id %>">
    <div class="ping_pong_game_date"><em><%= g.date.to_formatted_s(:rfc822) %></em></div>
    <div class="ping_pong_player_one_name"><span><%= g.player_one.name %></span></div>
    <div class="ping_pong_score">
      <div class="player_one_score"><span><%= g.player_one_score %></span></div>
      <div class="score_hyphen"><span>-</span></div>
      <div class="player_one_score"><span><%= g.player_two_score %></span></div>
    </div>
    <div class="ping_pong_player_two_name"><span><%= g.player_two.name %></span></div>
  </div>
<% end %>
<% if @ping_pong_games.none? %>
  <div class="center"><em>No games to show yet.</em></div>
<% end %>
</div>


<div class="list-button-container">
  <%= link_to 'new ping pong game', new_ping_pong_game_path, class: "button round" %>
</div>

app/views/ping_pong/new_game.html.erb
<div class="title">
  <h2>new ping pong game</h2>
</div>

<%= render partial: 'form', locals: {ping_pong_game: @ping_pong_game, target: ping_pong_games_path, cancel: ping_pong_path, method: :post, players: @players} %>

app/views/players/_form.html.erb
<%= simple_form_for :player, url: target, method: method do |f| %>
  <% if player.errors.any? %>
    <% player.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  <% end %>

  <%= f.input :name, autofocus: true  %>
  <div class="center form-button-container">
    <%= f.button :button, 'save', type: "submit", class: "button round" %>
    <%= link_to 'cancel', target, class: "button round" %>
  </div>
<% end %>

app/views/players/edit.html.erb
<div class="title">
  <h2>edit player</h2>
</div>

<%= render partial: 'form', locals: {player: @player, target: player_path(@player), method: :patch} %>

app/views/players/index.html.erb
<div class="title">
  <h2>players</h2>
</div>

<div class="link-list">
  <% @players.each do |player| %>
  <div class="link-list-item" %>
    <%= link_to player.name, player %>
  </div>
  <% end %>

  <% if @players.none? %>
    <div class="center"><em>No players to show yet.</em></div>
  <% end %>

  <div class="list-button-container">
  <%= link_to 'new player', new_player_path, class: "button round" %>
  </div>
</div>

app/views/players/new.html.erb
<div class="title">
  <h2>new player</h2>
</div>

<%= render partial: 'form', locals: {player: @player, target: players_path, method: :post} %>

app/views/players/show.html.erb
<div class="title">
  <h2>player stats</h2>
</div>

<div class="center">
  <p>name: <%= @player.name %></p>
</div>

<div class="list-button-container">
  <%= link_to 'edit player', edit_player_path(@player), class: "button round" %>
</div>

app/views/users/index.html.erb
<div class="title">
  <h2>users</h2>
</div>

<div class="link-list">
  <% @users.each do |user| %>
  <div class="link-list-item" %>
    <%= link_to user.name, user %>
  </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="title">
  <h2>create user</h2>
</div>

<%= simple_form_for :user, url: users_path do |f| %>
  <%= f.input :name %>
  <%= f.submit 'save' %>
<% end %>